{"content":"---\ntitle: \"Handling COM Interop Exceptions\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\nhelpviewer_keywords: \n  - \"unmanaged code, exceptions\"\n  - \"exceptions, unmanaged code\"\n  - \"HRESULTs\"\n  - \"exceptions, COM interop\"\n  - \"COM interop, exceptions\"\nms.assetid: e6104aa8-8e5f-4069-b864-def85579c96c\nauthor: \"mairaw\"\nms.author: \"mairaw\"\n---\n# Handling COM Interop Exceptions\nManaged and unmanaged code can work together to handle exceptions. If a method throws an exception in managed code, the common language runtime can pass an HRESULT to a COM object. If a method fails in unmanaged code by returning a failure HRESULT, the runtime throws an exception that can be caught by managed code.  \n  \n The runtime automatically maps the HRESULT from COM interop to more specific exceptions. For example, E_ACCESSDENIED becomes <xref:System.UnauthorizedAccessException>, E_OUTOFMEMORY becomes <xref:System.OutOfMemoryException>, and so on.  \n  \n If the HRESULT is a custom result or if it is unknown to the runtime, the runtime passes a generic <xref:System.Runtime.InteropServices.COMException> to the client. The **ErrorCode** property of the **COMException** contains the HRESULT value.  \n  \n## Working with IErrorInfo  \n When an error is passed from COM to managed code, the runtime populates the exception object with error information. COM objects that support IErrorInfo and return HRESULTS provide this information to managed code exceptions. For example, the runtime maps the Description from the COM error to the exception's <xref:System.Exception.Message%2A> property. If the HRESULT provides no additional error information, the runtime fills many of the exception's properties with default values.  \n  \n If a method fails in unmanaged code, an exception can be passed to a managed code segment. The topic [HRESULTS and Exceptions](../../../docs/framework/interop/how-to-map-hresults-and-exceptions.md) contains a table showing how HRESULTS map to runtime exception objects.  \n\n## See also\n\n- [Exceptions](index.md)\n","nodes":[{"pos":[4,346],"embed":true,"restype":"x-metadata","content":"title: \"Handling COM Interop Exceptions\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\nhelpviewer_keywords: \n  - \"unmanaged code, exceptions\"\n  - \"exceptions, unmanaged code\"\n  - \"HRESULTs\"\n  - \"exceptions, COM interop\"\n  - \"COM interop, exceptions\"\nms.assetid: e6104aa8-8e5f-4069-b864-def85579c96c\nauthor: \"mairaw\"\nms.author: \"mairaw\"","nodes":[{"content":"Handling COM Interop Exceptions","nodes":[{"pos":[0,31],"content":"Handling COM Interop Exceptions","nodes":[{"content":"Handling COM Interop Exceptions","pos":[0,31]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[353,384],"content":"Handling COM Interop Exceptions","linkify":"Handling COM Interop Exceptions","nodes":[{"content":"Handling COM Interop Exceptions","pos":[0,31]}]},{"content":"Managed and unmanaged code can work together to handle exceptions.","pos":[385,451]},{"content":"If a method throws an exception in managed code, the common language runtime can pass an HRESULT to a COM object.","pos":[452,565]},{"content":"If a method fails in unmanaged code by returning a failure HRESULT, the runtime throws an exception that can be caught by managed code.","pos":[566,701]},{"content":"The runtime automatically maps the HRESULT from COM interop to more specific exceptions.","pos":[708,796]},{"content":"For example, E_ACCESSDENIED becomes <ph id=\"ph1\">&lt;xref:System.UnauthorizedAccessException&gt;</ph>, E_OUTOFMEMORY becomes <ph id=\"ph2\">&lt;xref:System.OutOfMemoryException&gt;</ph>, and so on.","pos":[797,944],"source":" For example, E_ACCESSDENIED becomes <xref:System.UnauthorizedAccessException>, E_OUTOFMEMORY becomes <xref:System.OutOfMemoryException>, and so on."},{"content":"If the HRESULT is a custom result or if it is unknown to the runtime, the runtime passes a generic <ph id=\"ph1\">&lt;xref:System.Runtime.InteropServices.COMException&gt;</ph> to the client.","pos":[951,1115],"source":"If the HRESULT is a custom result or if it is unknown to the runtime, the runtime passes a generic <xref:System.Runtime.InteropServices.COMException> to the client."},{"content":"The <bpt id=\"p1\">**</bpt>ErrorCode<ept id=\"p1\">**</ept> property of the <bpt id=\"p2\">**</bpt>COMException<ept id=\"p2\">**</ept> contains the HRESULT value.","pos":[1116,1194],"source":" The **ErrorCode** property of the **COMException** contains the HRESULT value."},{"pos":[1203,1226],"content":"Working with IErrorInfo","linkify":"Working with IErrorInfo","nodes":[{"content":"Working with IErrorInfo","pos":[0,23]}]},{"content":"When an error is passed from COM to managed code, the runtime populates the exception object with error information.","pos":[1230,1346]},{"content":"COM objects that support IErrorInfo and return HRESULTS provide this information to managed code exceptions.","pos":[1347,1455]},{"content":"For example, the runtime maps the Description from the COM error to the exception's <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property.","pos":[1456,1584],"source":" For example, the runtime maps the Description from the COM error to the exception's <xref:System.Exception.Message%2A> property."},{"content":"If the HRESULT provides no additional error information, the runtime fills many of the exception's properties with default values.","pos":[1585,1715]},{"content":"If a method fails in unmanaged code, an exception can be passed to a managed code segment.","pos":[1722,1812]},{"content":"The topic <bpt id=\"p1\">[</bpt>HRESULTS and Exceptions<ept id=\"p1\">](../../../docs/framework/interop/how-to-map-hresults-and-exceptions.md)</ept> contains a table showing how HRESULTS map to runtime exception objects.","pos":[1813,1991],"source":" The topic [HRESULTS and Exceptions](../../../docs/framework/interop/how-to-map-hresults-and-exceptions.md) contains a table showing how HRESULTS map to runtime exception objects."},{"pos":[1998,2006],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[2010,2032],"content":"<bpt id=\"p1\">[</bpt>Exceptions<ept id=\"p1\">](index.md)</ept>","source":"[Exceptions](index.md)"}]}