{"content":"---\ntitle: \"Chaining Tasks by Using Continuation Tasks | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: dotnet-standard\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nhelpviewer_keywords: \n  - \"tasks, continuations\"\nms.assetid: 0b45e9a2-de28-46ce-8212-1817280ed42d\ncaps.latest.revision: 30\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\nmanager: \"wpickett\"\n---\n# Chaining Tasks by Using Continuation Tasks\nIn asynchronous programming, it is very common for one asynchronous operation, on completion, to invoke a second operation and pass data to it. Traditionally, this has been done by using callback methods. In the Task Parallel Library, the same functionality is provided by *continuation tasks*. A continuation task (also known just as a continuation) is an asynchronous task that is invoked by another task, which is known as the *antecedent*, when the antecedent finishes.  \n  \n Continuations are relatively easy to use, but are nevertheless very powerful and flexible. For example, you can:  \n  \n-   Pass data from the antecedent to the continuation.  \n  \n-   Specify the precise conditions under which the continuation will be invoked or not invoked.  \n  \n-   Cancel a continuation either before it starts or cooperatively as it is running.  \n  \n-   Provide hints about how the continuation should be scheduled.  \n  \n-   Invoke multiple continuations from the same antecedent.  \n  \n-   Invoke one continuation when all or any one of multiple antecedents complete.  \n  \n-   Chain continuations one after another to any arbitrary length.  \n  \n-   Use a continuation to handle exceptions thrown by the antecedent.  \n  \n## About continuations  \n A continuation is a task that is created in the <xref:System.Threading.Tasks.TaskStatus> state. It is activated automatically when its antecedent task or tasks complete. Calling <xref:System.Threading.Tasks.Task.Start%2A?displayProperty=fullName> on a continuation in user code throws an <xref:System.InvalidOperationException?displayProperty=fullName> exception.  \n  \n A continuation is itself a <xref:System.Threading.Tasks.Task> and does not block the thread on which it is started. Call the <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=fullName> method to block until the continuation task finishes.  \n  \n## Creating a continuation for a single antecedent  \n You create a continuation that executes when its antecedent has completed by calling the <xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName> method. The following example shows the basic pattern, (for clarity, exception handling is omitted). It executes an antecedent task, `taskA`, that returns a <xref:System.DayOfWeek> object that indicates the name of the current day of the week. When the antecedent finishes, the continuation task, `taskB`, is passed the antecedent and displays a string that includes its result.  \n  \n [!code-csharp[TPL_Continuations#1](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/simple1.cs#1)]\n [!code-vb[TPL_Continuations#1](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/simple1.vb#1)]  \n  \n## Creating a continuation for multiple antecedents  \n You can also create a continuation that will run when any or all of a group of tasks has completed. To execute a continuation when all antecedent tasks have completed, you call the static (`Shared` in Visual Basic) <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName> method or the instance <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName> method. To execute a continuation when any of the antecedent tasks has completed, you call the static (`Shared` in Visual Basic) <xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName> method or the instance <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAny%2A?displayProperty=fullName> method.  \n  \n Note that calls to the <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName> and <xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName> overloads do not block the calling thread.  However, you typically call all but the <xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName> and  <xref:System.Threading.Tasks.Task.WhenAll%28System.Threading.Tasks.Task%5B%5D%29?displayProperty=fullName> methods to retrieve the returned  <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property, which does block the calling thread.  \n  \n The following example calls the <xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName> method to create a continuation task that reflects the results of its ten antecedent tasks. Each antecedent task squares an index value that ranges from one to ten. If the antecedents complete successfully (their <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property is <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName>), the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property of the continuation is an array of the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> values returned by each antecedent. The example adds them to compute the sum of squares for all numbers between one and ten.  \n  \n [!code-csharp[TPL_Continuations#5](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/whenall1.cs#5)]\n [!code-vb[TPL_Continuations#5](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/whenall1.vb#5)]  \n  \n## Continuation options  \n When you create a single-task continuation, you can use a <xref:System.Threading.Tasks.Task.ContinueWith%2A> overload that takes a <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> enumeration value to specify the conditions under which the continuation starts. For example, you can specify that the continuation is to run only if the antecedent completes successfully, or only if it completes in a faulted state. If the condition is not true when the antecedent is ready to invoke the continuation, the continuation transitions directly to the <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state and cannot be started after that.  \n  \n A number of multi-task continuation methods, such as overloads of the <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName> method, also include a <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> parameter. Only a subset of all <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> enumeration members are valid, however. You can specify <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> values that have counterparts in the <xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName> enumeration, such as <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>, <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>, and <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>. If you specify any of the `NotOn` or `OnlyOn` options with a multi-task continuation, an <xref:System.ArgumentOutOfRangeException> exception will be thrown at run time.  \n  \n For more information on task continuation options, see the <xref:System.Threading.Tasks.TaskContinuationOptions> topic.  \n  \n## Passing Data to a Continuation  \n The <xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName> method passes a reference to the antecedent to the user delegate of the continuation as an argument. If the antecedent is a <xref:System.Threading.Tasks.Task%601?displayProperty=fullName> object, and the task ran until it was completed, then the continuation can access the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property of the task.  \n  \n The <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property blocks until the task has completed. However, if the task was canceled or faulted, attempting to access the <xref:System.Threading.Tasks.Task%601.Result%2A> property throws an <xref:System.AggregateException> exception. You can avoid this problem by using the <xref:System.Threading.Tasks.TaskContinuationOptions> option, as shown in the following example.  \n  \n [!code-csharp[TPL_Continuations#2](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result1.cs#2)]\n [!code-vb[TPL_Continuations#2](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result1.vb#2)]  \n  \n If you want the continuation to run even if the antecedent did not run to successful completion, you must guard against the exception. One approach is to test the <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property of the antecedent, and only attempt to access the <xref:System.Threading.Tasks.Task%601.Result%2A> property if the status is not <xref:System.Threading.Tasks.TaskStatus> or <xref:System.Threading.Tasks.TaskStatus>. You can also examine the <xref:System.Threading.Tasks.Task.Exception%2A> property of the antecedent. For more information, see [Exception Handling](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md). The following example modifies the previous example to access antecedent's <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property only if its status is <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName>.  \n  \n [!code-csharp[TPL_Continuations#7](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result2.cs#7)]\n [!code-vb[TPL_Continuations#7](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result2.vb#7)]  \n  \n## Canceling a Continuation  \n The <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property of a continuation is set to <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> in the following situations:  \n  \n-   It throws an <xref:System.OperationCanceledException> exception in response to a cancellation request. Just as with any task, if the exception contains the same token that was passed to the continuation, it is treated as an acknowledgement of cooperative cancellation.  \n  \n-   The continuation is passed a <xref:System.Threading.CancellationToken?displayProperty=fullName> whose <xref:System.Threading.CancellationToken.IsCancellationRequested%2A> property is `true`. In this case, the continuation does not start, and it transitions to the <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state.  \n  \n-   The continuation never runs because the condition set by its <xref:System.Threading.Tasks.TaskContinuationOptions> argument was not met. For example, if an antecedent goes into a <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state, its continuation that was passed the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option will not run but will transition to the <xref:System.Threading.Tasks.TaskStatus> state.  \n  \n If a task and its continuation represent two parts of the same logical operation, you can pass the same cancellation token to both tasks, as shown in the following example. It consists of an antecedent that generates a list of integers that are divisible by 33, which it passes to the continuation. The continuation in turn displays the list. Both the antecedent and the continuation pause regularly for random intervals. In addition, a <xref:System.Threading.Timer?displayProperty=fullName> object is used to execute the `Elapsed` method after a five-second timeout interval. This calls the <xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName> method, which causes the currently executing task to call the <xref:System.Threading.CancellationToken.ThrowIfCancellationRequested%2A?displayProperty=fullName> method. Whether the <xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName> method is called when the antecedent or its continuation is executing depends on the duration of the randomly generated pauses. If the antecedent is canceled, the continuation will not start. If the antecedent is not canceled, the token can still be used to cancel the continuation.  \n  \n [!code-csharp[TPL_Continuations#3](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation1.cs#3)]\n [!code-vb[TPL_Continuations#3](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation1.vb#3)]  \n  \n You can also prevent a continuation from executing if its antecedent is canceled without supplying the continuation a cancellation token by specifying the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option when you create the continuation. The following is a simple example.  \n  \n [!code-csharp[TPL_Continuations#8](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation2.cs#8)]\n [!code-vb[TPL_Continuations#8](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation2.vb#8)]  \n  \n After a continuation goes into the <xref:System.Threading.Tasks.TaskStatus> state, it may affect continuations that follow, depending on the <xref:System.Threading.Tasks.TaskContinuationOptions> that were specified for those continuations.  \n  \n Continuations that are disposed will not start.  \n  \n## Continuations and Child Tasks  \n A continuation does not run until the antecedent and all of its attached child tasks have completed. The continuation does not wait for detached child tasks to finish. The following two examples illustrate child tasks that are attached to and detached from an antecedent that creates a continuation. In the following example, the continuation runs only after all child tasks have completed, and running the example multiple times produces identical output each time. Note that the example launches the antecedent by calling the <xref:System.Threading.Tasks.TaskFactory.StartNew%2A?displayProperty=fullName> method, since by default the <xref:System.Threading.Tasks.Task.Run%2A?displayProperty=fullName> method creates a parent task whose default task creation option is <xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName>.  \n  \n [!code-csharp[TPL_Continuations#9](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/attached1.cs#9)]\n [!code-vb[TPL_Continuations#9](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/attached1.vb#9)]  \n  \n If child tasks are detached from the antecedent, however, the continuation runs as soon as the antecedent has terminated, regardless of the state of the child tasks. As a result, multiple runs of the following example can produce variable output that depends on how the task scheduler handled each child task.  \n  \n [!code-csharp[TPL_Continuations#10](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/detached1.cs#10)]\n [!code-vb[TPL_Continuations#10](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/detached1.vb#10)]  \n  \n The final status of the antecedent task depends on the final status of any attached child tasks. The status of detached child tasks does not affect the parent. For more information, see [Attached and Detached Child Tasks](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md).  \n  \n## Associating State with Continuations  \n You can associate arbitrary state with a task continuation. The <xref:System.Threading.Tasks.Task.ContinueWith%2A> method provides overloaded versions that each take an <xref:System.Object> value that represents the state of the continuation. You can later access this state object by using the <xref:System.Threading.Tasks.Task.AsyncState%2A?displayProperty=fullName> property. This state object is `null` if you do not provide a value.  \n  \n Continuation state is useful when you convert existing code that uses the [Asynchronous Programming Model (APM)](../../../docs/standard/asynchronous-programming-patterns/asynchronous-programming-model-apm.md) to use the TPL. In the APM, you typically provide object state in the **Begin*Method*** method and later access that state by using the <xref:System.IAsyncResult.AsyncState%2A?displayProperty=fullName> property. By using the <xref:System.Threading.Tasks.Task.ContinueWith%2A> method, you can preserve this state when you convert code that uses the APM to use the TPL.  \n  \n Continuation state can also be useful when you work with <xref:System.Threading.Tasks.Task> objects in the [!INCLUDE[vsprvs](../../../includes/vsprvs-md.md)] debugger. For example, in the **Parallel Tasks** window, the **Task** column displays the string representation of the state object for each task. For more information about the **Parallel Tasks** window, see [Using the Tasks Window](/visualstudio/debugger/using-the-tasks-window).  \n  \n The following example shows how to use continuation state. It creates a chain of continuation tasks. Each task provides the current time, a <xref:System.DateTime> object, for the `state` parameter of the <xref:System.Threading.Tasks.Task.ContinueWith%2A> method. Each <xref:System.DateTime> object represents the time at which the continuation task is created. Each task produces as its result a second <xref:System.DateTime> object that represents the time at which the task finishes. After all tasks finish, this example displays the creation time and the time at which each continuation task finishes.  \n  \n [!code-csharp[TPL_ContinuationState#1](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuationstate/cs/continuationstate.cs#1)]\n [!code-vb[TPL_ContinuationState#1](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuationstate/vb/continuationstate.vb#1)]  \n  \n## Handling Exceptions Thrown from Continuations  \n An antecedent-continuation relationship is not a parent-child relationship. Exceptions thrown by continuations are not propagated to the antecedent. Therefore, handle exceptions thrown by continuations as you would handle them in any other task, as follows:  \n  \n-   You can use the <xref:System.Threading.Tasks.Task.Wait%2A>, <xref:System.Threading.Tasks.Task.WaitAll%2A>, or <xref:System.Threading.Tasks.Task.WaitAny%2A> method, or its generic counterpart, to wait on the continuation. You can wait for an antecedent and its continuations in the same `try` statement, as shown in the following example.  \n  \n     [!code-csharp[TPL_Continuations#6](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception1.cs#6)]\n     [!code-vb[TPL_Continuations#6](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception1.vb#6)]  \n  \n-   You can use a second continuation to observe the <xref:System.Threading.Tasks.Task.Exception%2A> property of the first continuation. In the following example, a task attempts to read from a non-existent file. The continuation then displays information about the exception in the antecedent task.  \n  \n     [!code-csharp[TPL_Continuations#4](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#4)]\n     [!code-vb[TPL_Continuations#4](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#4)]  \n  \n     Because it was run with the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option, the continuation executes only if an exception occurs in the antecedent, and therefore it can assume that the antecedent's <xref:System.Threading.Tasks.Task.Exception%2A> property is not `null`. If the continuation executes whether or not an exception is thrown in the antecedent, it would have to check whether the antecedent's <xref:System.Threading.Tasks.Task.Exception%2A> property is not `null` before attempting to handle the exception, as the following code fragment shows.  \n  \n     [!code-csharp[TPL_Continuations#11](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#11)]\n     [!code-vb[TPL_Continuations#11](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#11)]  \n  \n     For more information, see [Exception Handling](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md) and [NIB: How to: Handle Exceptions Thrown by Tasks](http://msdn.microsoft.com/en-us/d6c47ec8-9de9-4880-beb3-ff19ae51565d).  \n  \n-   If the continuation is an attached child task that was created by using the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option, its exceptions will be propagated by the parent back to the calling thread, as is the case in any other attached child. For more information, see [Attached and Detached Child Tasks](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md).  \n  \n## See Also  \n [Task Parallel Library (TPL)](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md)","nodes":[{"pos":[4,405],"embed":true,"restype":"x-metadata","content":"title: \"Chaining Tasks by Using Continuation Tasks | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: dotnet-standard\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nhelpviewer_keywords: \n  - \"tasks, continuations\"\nms.assetid: 0b45e9a2-de28-46ce-8212-1817280ed42d\ncaps.latest.revision: 30\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\nmanager: \"wpickett\"","nodes":[{"content":"Chaining Tasks by Using Continuation Tasks | Microsoft Docs","nodes":[{"pos":[0,59],"content":"Chaining Tasks by Using Continuation Tasks | Microsoft Docs","nodes":[{"content":"Chaining Tasks by Using Continuation Tasks | Microsoft Docs","pos":[0,59]}]}],"path":["title"]}],"yml":true},{"pos":[412,454],"content":"Chaining Tasks by Using Continuation Tasks","linkify":"Chaining Tasks by Using Continuation Tasks","nodes":[{"content":"Chaining Tasks by Using Continuation Tasks","pos":[0,42]}]},{"content":"In asynchronous programming, it is very common for one asynchronous operation, on completion, to invoke a second operation and pass data to it.","pos":[455,598]},{"content":"Traditionally, this has been done by using callback methods.","pos":[599,659]},{"content":"In the Task Parallel Library, the same functionality is provided by <bpt id=\"p1\">*</bpt>continuation tasks<ept id=\"p1\">*</ept>.","pos":[660,749],"source":" In the Task Parallel Library, the same functionality is provided by *continuation tasks*."},{"content":"A continuation task (also known just as a continuation) is an asynchronous task that is invoked by another task, which is known as the <bpt id=\"p1\">*</bpt>antecedent<ept id=\"p1\">*</ept>, when the antecedent finishes.","pos":[750,928],"source":" A continuation task (also known just as a continuation) is an asynchronous task that is invoked by another task, which is known as the *antecedent*, when the antecedent finishes."},{"content":"Continuations are relatively easy to use, but are nevertheless very powerful and flexible.","pos":[935,1025]},{"content":"For example, you can:","pos":[1026,1047]},{"content":"Pass data from the antecedent to the continuation.","pos":[1057,1107]},{"content":"Specify the precise conditions under which the continuation will be invoked or not invoked.","pos":[1117,1208]},{"content":"Cancel a continuation either before it starts or cooperatively as it is running.","pos":[1218,1298]},{"content":"Provide hints about how the continuation should be scheduled.","pos":[1308,1369]},{"content":"Invoke multiple continuations from the same antecedent.","pos":[1379,1434]},{"content":"Invoke one continuation when all or any one of multiple antecedents complete.","pos":[1444,1521]},{"content":"Chain continuations one after another to any arbitrary length.","pos":[1531,1593]},{"content":"Use a continuation to handle exceptions thrown by the antecedent.","pos":[1603,1668]},{"pos":[1677,1696],"content":"About continuations","linkify":"About continuations","nodes":[{"content":"About continuations","pos":[0,19]}]},{"content":"A continuation is a task that is created in the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskStatus&gt;</ph> state.","pos":[1700,1795],"source":"A continuation is a task that is created in the <xref:System.Threading.Tasks.TaskStatus> state."},{"content":"It is activated automatically when its antecedent task or tasks complete.","pos":[1796,1869]},{"content":"Calling <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Start%2A?displayProperty=fullName&gt;</ph> on a continuation in user code throws an <ph id=\"ph2\">&lt;xref:System.InvalidOperationException?displayProperty=fullName&gt;</ph> exception.","pos":[1870,2063],"source":" Calling <xref:System.Threading.Tasks.Task.Start%2A?displayProperty=fullName> on a continuation in user code throws an <xref:System.InvalidOperationException?displayProperty=fullName> exception."},{"content":"A continuation is itself a <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task&gt;</ph> and does not block the thread on which it is started.","pos":[2070,2185],"source":"A continuation is itself a <xref:System.Threading.Tasks.Task> and does not block the thread on which it is started."},{"content":"Call the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=fullName&gt;</ph> method to block until the continuation task finishes.","pos":[2186,2316],"source":" Call the <xref:System.Threading.Tasks.Task.Wait%2A?displayProperty=fullName> method to block until the continuation task finishes."},{"pos":[2325,2372],"content":"Creating a continuation for a single antecedent","linkify":"Creating a continuation for a single antecedent","nodes":[{"content":"Creating a continuation for a single antecedent","pos":[0,47]}]},{"content":"You create a continuation that executes when its antecedent has completed by calling the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName&gt;</ph> method.","pos":[2376,2548],"source":"You create a continuation that executes when its antecedent has completed by calling the <xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName> method."},{"content":"The following example shows the basic pattern, (for clarity, exception handling is omitted).","pos":[2549,2641]},{"content":"It executes an antecedent task, <ph id=\"ph1\">`taskA`</ph>, that returns a <ph id=\"ph2\">&lt;xref:System.DayOfWeek&gt;</ph> object that indicates the name of the current day of the week.","pos":[2642,2784],"source":" It executes an antecedent task, `taskA`, that returns a <xref:System.DayOfWeek> object that indicates the name of the current day of the week."},{"content":"When the antecedent finishes, the continuation task, <ph id=\"ph1\">`taskB`</ph>, is passed the antecedent and displays a string that includes its result.","pos":[2785,2919],"source":" When the antecedent finishes, the continuation task, `taskB`, is passed the antecedent and displays a string that includes its result."},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#1<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/simple1.cs#1)</ept><ept id=\"p1\">]</ept>","pos":[2926,3046],"source":"[!code-csharp[TPL_Continuations#1](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/simple1.cs#1)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#1<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/simple1.vb#1)</ept><ept id=\"p1\">]</ept>","pos":[3048,3169],"source":"[!code-vb[TPL_Continuations#1](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/simple1.vb#1)]"},{"pos":[3178,3226],"content":"Creating a continuation for multiple antecedents","linkify":"Creating a continuation for multiple antecedents","nodes":[{"content":"Creating a continuation for multiple antecedents","pos":[0,48]}]},{"content":"You can also create a continuation that will run when any or all of a group of tasks has completed.","pos":[3230,3329]},{"content":"To execute a continuation when all antecedent tasks have completed, you call the static (<ph id=\"ph1\">`Shared`</ph> in Visual Basic) <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName&gt;</ph> method or the instance <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName&gt;</ph> method.","pos":[3330,3632],"source":" To execute a continuation when all antecedent tasks have completed, you call the static (`Shared` in Visual Basic) <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName> method or the instance <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName> method."},{"content":"To execute a continuation when any of the antecedent tasks has completed, you call the static (<ph id=\"ph1\">`Shared`</ph> in Visual Basic) <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName&gt;</ph> method or the instance <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskFactory.ContinueWhenAny%2A?displayProperty=fullName&gt;</ph> method.","pos":[3633,3941],"source":" To execute a continuation when any of the antecedent tasks has completed, you call the static (`Shared` in Visual Basic) <xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName> method or the instance <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAny%2A?displayProperty=fullName> method."},{"content":"Note that calls to the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName&gt;</ph> and <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName&gt;</ph> overloads do not block the calling thread.","pos":[3948,4159],"source":"Note that calls to the <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=fullName> and <xref:System.Threading.Tasks.Task.WhenAny%2A?displayProperty=fullName> overloads do not block the calling thread."},{"content":"However, you typically call all but the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName&gt;</ph> and  <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.WhenAll%28System.Threading.Tasks.Task%5B%5D%29?displayProperty=fullName&gt;</ph> methods to retrieve the returned  <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> property, which does block the calling thread.","pos":[4161,4612],"source":"  However, you typically call all but the <xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName> and  <xref:System.Threading.Tasks.Task.WhenAll%28System.Threading.Tasks.Task%5B%5D%29?displayProperty=fullName> methods to retrieve the returned  <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property, which does block the calling thread."},{"content":"The following example calls the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName&gt;</ph> method to create a continuation task that reflects the results of its ten antecedent tasks.","pos":[4619,4887],"source":"The following example calls the <xref:System.Threading.Tasks.Task.WhenAll%28System.Collections.Generic.IEnumerable%7BSystem.Threading.Tasks.Task%7D%29?displayProperty=fullName> method to create a continuation task that reflects the results of its ten antecedent tasks."},{"content":"Each antecedent task squares an index value that ranges from one to ten.","pos":[4888,4960]},{"content":"If the antecedents complete successfully (their <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName&gt;</ph> property is <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph>), the <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> property of the continuation is an array of the <ph id=\"ph4\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> values returned by each antecedent.","pos":[4961,5394],"source":" If the antecedents complete successfully (their <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property is <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName>), the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property of the continuation is an array of the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> values returned by each antecedent."},{"content":"The example adds them to compute the sum of squares for all numbers between one and ten.","pos":[5395,5483]},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#5<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/whenall1.cs#5)</ept><ept id=\"p1\">]</ept>","pos":[5490,5611],"source":"[!code-csharp[TPL_Continuations#5](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/whenall1.cs#5)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#5<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/whenall1.vb#5)</ept><ept id=\"p1\">]</ept>","pos":[5613,5735],"source":"[!code-vb[TPL_Continuations#5](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/whenall1.vb#5)]"},{"pos":[5744,5764],"content":"Continuation options","linkify":"Continuation options","nodes":[{"content":"Continuation options","pos":[0,20]}]},{"content":"When you create a single-task continuation, you can use a <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A&gt;</ph> overload that takes a <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> enumeration value to specify the conditions under which the continuation starts.","pos":[5768,6058],"source":"When you create a single-task continuation, you can use a <xref:System.Threading.Tasks.Task.ContinueWith%2A> overload that takes a <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> enumeration value to specify the conditions under which the continuation starts."},{"content":"For example, you can specify that the continuation is to run only if the antecedent completes successfully, or only if it completes in a faulted state.","pos":[6059,6210]},{"content":"If the condition is not true when the antecedent is ready to invoke the continuation, the continuation transitions directly to the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph> state and cannot be started after that.","pos":[6211,6447],"source":" If the condition is not true when the antecedent is ready to invoke the continuation, the continuation transitions directly to the <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state and cannot be started after that."},{"content":"A number of multi-task continuation methods, such as overloads of the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName&gt;</ph> method, also include a <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> parameter.","pos":[6454,6722],"source":"A number of multi-task continuation methods, such as overloads of the <xref:System.Threading.Tasks.TaskFactory.ContinueWhenAll%2A?displayProperty=fullName> method, also include a <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> parameter."},{"content":"Only a subset of all <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> enumeration members are valid, however.","pos":[6723,6862],"source":" Only a subset of all <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> enumeration members are valid, however."},{"content":"You can specify <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> values that have counterparts in the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName&gt;</ph> enumeration, such as <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph>, <ph id=\"ph4\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph>, and <ph id=\"ph5\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph>.","pos":[6863,7334],"source":" You can specify <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> values that have counterparts in the <xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName> enumeration, such as <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>, <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>, and <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName>."},{"content":"If you specify any of the <ph id=\"ph1\">`NotOn`</ph> or <ph id=\"ph2\">`OnlyOn`</ph> options with a multi-task continuation, an <ph id=\"ph3\">&lt;xref:System.ArgumentOutOfRangeException&gt;</ph> exception will be thrown at run time.","pos":[7335,7503],"source":" If you specify any of the `NotOn` or `OnlyOn` options with a multi-task continuation, an <xref:System.ArgumentOutOfRangeException> exception will be thrown at run time."},{"content":"For more information on task continuation options, see the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions&gt;</ph> topic.","pos":[7510,7629],"source":"For more information on task continuation options, see the <xref:System.Threading.Tasks.TaskContinuationOptions> topic."},{"pos":[7638,7668],"content":"Passing Data to a Continuation","linkify":"Passing Data to a Continuation","nodes":[{"content":"Passing Data to a Continuation","pos":[0,30]}]},{"content":"The <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName&gt;</ph> method passes a reference to the antecedent to the user delegate of the continuation as an argument.","pos":[7672,7852],"source":"The <xref:System.Threading.Tasks.Task.ContinueWith%2A?displayProperty=fullName> method passes a reference to the antecedent to the user delegate of the continuation as an argument."},{"content":"If the antecedent is a <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task%601?displayProperty=fullName&gt;</ph> object, and the task ran until it was completed, then the continuation can access the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> property of the task.","pos":[7853,8121],"source":" If the antecedent is a <xref:System.Threading.Tasks.Task%601?displayProperty=fullName> object, and the task ran until it was completed, then the continuation can access the <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property of the task."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> property blocks until the task has completed.","pos":[8128,8251],"source":"The <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property blocks until the task has completed."},{"content":"However, if the task was canceled or faulted, attempting to access the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A&gt;</ph> property throws an <ph id=\"ph2\">&lt;xref:System.AggregateException&gt;</ph> exception.","pos":[8252,8434],"source":" However, if the task was canceled or faulted, attempting to access the <xref:System.Threading.Tasks.Task%601.Result%2A> property throws an <xref:System.AggregateException> exception."},{"content":"You can avoid this problem by using the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions&gt;</ph> option, as shown in the following example.","pos":[8435,8571],"source":" You can avoid this problem by using the <xref:System.Threading.Tasks.TaskContinuationOptions> option, as shown in the following example."},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#2<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result1.cs#2)</ept><ept id=\"p1\">]</ept>","pos":[8578,8698],"source":"[!code-csharp[TPL_Continuations#2](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result1.cs#2)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#2<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result1.vb#2)</ept><ept id=\"p1\">]</ept>","pos":[8700,8821],"source":"[!code-vb[TPL_Continuations#2](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result1.vb#2)]"},{"content":"If you want the continuation to run even if the antecedent did not run to successful completion, you must guard against the exception.","pos":[8828,8962]},{"content":"One approach is to test the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName&gt;</ph> property of the antecedent, and only attempt to access the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A&gt;</ph> property if the status is not <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskStatus&gt;</ph> or <ph id=\"ph4\">&lt;xref:System.Threading.Tasks.TaskStatus&gt;</ph>.","pos":[8963,9284],"source":" One approach is to test the <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property of the antecedent, and only attempt to access the <xref:System.Threading.Tasks.Task%601.Result%2A> property if the status is not <xref:System.Threading.Tasks.TaskStatus> or <xref:System.Threading.Tasks.TaskStatus>."},{"content":"You can also examine the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Exception%2A&gt;</ph> property of the antecedent.","pos":[9285,9385],"source":" You can also examine the <xref:System.Threading.Tasks.Task.Exception%2A> property of the antecedent."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md)</ept>.","pos":[9386,9522],"source":" For more information, see [Exception Handling](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md)."},{"content":"The following example modifies the previous example to access antecedent's <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName&gt;</ph> property only if its status is <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph>.","pos":[9523,9769],"source":" The following example modifies the previous example to access antecedent's <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property only if its status is <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName>."},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#7<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result2.cs#7)</ept><ept id=\"p1\">]</ept>","pos":[9776,9896],"source":"[!code-csharp[TPL_Continuations#7](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/result2.cs#7)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#7<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result2.vb#7)</ept><ept id=\"p1\">]</ept>","pos":[9898,10019],"source":"[!code-vb[TPL_Continuations#7](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/result2.vb#7)]"},{"pos":[10028,10052],"content":"Canceling a Continuation","linkify":"Canceling a Continuation","nodes":[{"content":"Canceling a Continuation","pos":[0,24]}]},{"content":"The <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName&gt;</ph> property of a continuation is set to <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph> in the following situations:","pos":[10056,10261],"source":"The <xref:System.Threading.Tasks.Task.Status%2A?displayProperty=fullName> property of a continuation is set to <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> in the following situations:"},{"content":"It throws an <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph> exception in response to a cancellation request.","pos":[10271,10373],"source":"It throws an <xref:System.OperationCanceledException> exception in response to a cancellation request."},{"content":"Just as with any task, if the exception contains the same token that was passed to the continuation, it is treated as an acknowledgement of cooperative cancellation.","pos":[10374,10539]},{"content":"The continuation is passed a <ph id=\"ph1\">&lt;xref:System.Threading.CancellationToken?displayProperty=fullName&gt;</ph> whose <ph id=\"ph2\">&lt;xref:System.Threading.CancellationToken.IsCancellationRequested%2A&gt;</ph> property is <ph id=\"ph3\">`true`</ph>.","pos":[10549,10739],"source":"The continuation is passed a <xref:System.Threading.CancellationToken?displayProperty=fullName> whose <xref:System.Threading.CancellationToken.IsCancellationRequested%2A> property is `true`."},{"content":"In this case, the continuation does not start, and it transitions to the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph> state.","pos":[10740,10885],"source":" In this case, the continuation does not start, and it transitions to the <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state."},{"content":"The continuation never runs because the condition set by its <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions&gt;</ph> argument was not met.","pos":[10895,11031],"source":"The continuation never runs because the condition set by its <xref:System.Threading.Tasks.TaskContinuationOptions> argument was not met."},{"content":"For example, if an antecedent goes into a <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName&gt;</ph> state, its continuation that was passed the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> option will not run but will transition to the <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskStatus&gt;</ph> state.","pos":[11032,11357],"source":" For example, if an antecedent goes into a <xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName> state, its continuation that was passed the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option will not run but will transition to the <xref:System.Threading.Tasks.TaskStatus> state."},{"content":"If a task and its continuation represent two parts of the same logical operation, you can pass the same cancellation token to both tasks, as shown in the following example.","pos":[11364,11536]},{"content":"It consists of an antecedent that generates a list of integers that are divisible by 33, which it passes to the continuation.","pos":[11537,11662]},{"content":"The continuation in turn displays the list.","pos":[11663,11706]},{"content":"Both the antecedent and the continuation pause regularly for random intervals.","pos":[11707,11785]},{"content":"In addition, a <ph id=\"ph1\">&lt;xref:System.Threading.Timer?displayProperty=fullName&gt;</ph> object is used to execute the <ph id=\"ph2\">`Elapsed`</ph> method after a five-second timeout interval.","pos":[11786,11940],"source":" In addition, a <xref:System.Threading.Timer?displayProperty=fullName> object is used to execute the `Elapsed` method after a five-second timeout interval."},{"content":"This calls the <ph id=\"ph1\">&lt;xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName&gt;</ph> method, which causes the currently executing task to call the <ph id=\"ph2\">&lt;xref:System.Threading.CancellationToken.ThrowIfCancellationRequested%2A?displayProperty=fullName&gt;</ph> method.","pos":[11941,12207],"source":" This calls the <xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName> method, which causes the currently executing task to call the <xref:System.Threading.CancellationToken.ThrowIfCancellationRequested%2A?displayProperty=fullName> method."},{"content":"Whether the <ph id=\"ph1\">&lt;xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName&gt;</ph> method is called when the antecedent or its continuation is executing depends on the duration of the randomly generated pauses.","pos":[12208,12430],"source":" Whether the <xref:System.Threading.CancellationTokenSource.Cancel%2A?displayProperty=fullName> method is called when the antecedent or its continuation is executing depends on the duration of the randomly generated pauses."},{"content":"If the antecedent is canceled, the continuation will not start.","pos":[12431,12494]},{"content":"If the antecedent is not canceled, the token can still be used to cancel the continuation.","pos":[12495,12585]},{"pos":[12592,12847],"content":"[!code-csharp[TPL_Continuations#3](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation1.cs#3)]\n[!code-vb[TPL_Continuations#3](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation1.vb#3)]","leadings":[""," "],"nodes":[{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#3<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation1.cs#3)</ept><ept id=\"p1\">]</ept>","pos":[0,126],"source":"[!code-csharp[TPL_Continuations#3](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation1.cs#3)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#3<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation1.vb#3)</ept><ept id=\"p1\">]</ept>","pos":[127,254],"source":"[!code-vb[TPL_Continuations#3](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation1.vb#3)]"}]},{"content":"You can also prevent a continuation from executing if its antecedent is canceled without supplying the continuation a cancellation token by specifying the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> option when you create the continuation.","pos":[12854,13128],"source":"You can also prevent a continuation from executing if its antecedent is canceled without supplying the continuation a cancellation token by specifying the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option when you create the continuation."},{"content":"The following is a simple example.","pos":[13129,13163]},{"pos":[13170,13425],"content":"[!code-csharp[TPL_Continuations#8](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation2.cs#8)]\n[!code-vb[TPL_Continuations#8](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation2.vb#8)]","leadings":[""," "],"nodes":[{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#8<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation2.cs#8)</ept><ept id=\"p1\">]</ept>","pos":[0,126],"source":"[!code-csharp[TPL_Continuations#8](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/cancellation2.cs#8)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#8<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation2.vb#8)</ept><ept id=\"p1\">]</ept>","pos":[127,254],"source":"[!code-vb[TPL_Continuations#8](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/cancellation2.vb#8)]"}]},{"content":"After a continuation goes into the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskStatus&gt;</ph> state, it may affect continuations that follow, depending on the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions&gt;</ph> that were specified for those continuations.","pos":[13432,13671],"source":"After a continuation goes into the <xref:System.Threading.Tasks.TaskStatus> state, it may affect continuations that follow, depending on the <xref:System.Threading.Tasks.TaskContinuationOptions> that were specified for those continuations."},{"content":"Continuations that are disposed will not start.","pos":[13678,13725]},{"pos":[13734,13763],"content":"Continuations and Child Tasks","linkify":"Continuations and Child Tasks","nodes":[{"content":"Continuations and Child Tasks","pos":[0,29]}]},{"content":"A continuation does not run until the antecedent and all of its attached child tasks have completed.","pos":[13767,13867]},{"content":"The continuation does not wait for detached child tasks to finish.","pos":[13868,13934]},{"content":"The following two examples illustrate child tasks that are attached to and detached from an antecedent that creates a continuation.","pos":[13935,14066]},{"content":"In the following example, the continuation runs only after all child tasks have completed, and running the example multiple times produces identical output each time.","pos":[14067,14233]},{"content":"Note that the example launches the antecedent by calling the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskFactory.StartNew%2A?displayProperty=fullName&gt;</ph> method, since by default the <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.Run%2A?displayProperty=fullName&gt;</ph> method creates a parent task whose default task creation option is <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName&gt;</ph>.","pos":[14234,14612],"source":" Note that the example launches the antecedent by calling the <xref:System.Threading.Tasks.TaskFactory.StartNew%2A?displayProperty=fullName> method, since by default the <xref:System.Threading.Tasks.Task.Run%2A?displayProperty=fullName> method creates a parent task whose default task creation option is <xref:System.Threading.Tasks.TaskCreationOptions?displayProperty=fullName>."},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#9<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/attached1.cs#9)</ept><ept id=\"p1\">]</ept>","pos":[14619,14741],"source":"[!code-csharp[TPL_Continuations#9](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/attached1.cs#9)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#9<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/attached1.vb#9)</ept><ept id=\"p1\">]</ept>","pos":[14743,14866],"source":"[!code-vb[TPL_Continuations#9](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/attached1.vb#9)]"},{"content":"If child tasks are detached from the antecedent, however, the continuation runs as soon as the antecedent has terminated, regardless of the state of the child tasks.","pos":[14873,15038]},{"content":"As a result, multiple runs of the following example can produce variable output that depends on how the task scheduler handled each child task.","pos":[15039,15182]},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#10<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/detached1.cs#10)</ept><ept id=\"p1\">]</ept>","pos":[15189,15313],"source":"[!code-csharp[TPL_Continuations#10](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/detached1.cs#10)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#10<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/detached1.vb#10)</ept><ept id=\"p1\">]</ept>","pos":[15315,15440],"source":"[!code-vb[TPL_Continuations#10](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/detached1.vb#10)]"},{"content":"The final status of the antecedent task depends on the final status of any attached child tasks.","pos":[15447,15543]},{"content":"The status of detached child tasks does not affect the parent.","pos":[15544,15606]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Attached and Detached Child Tasks<ept id=\"p1\">](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md)</ept>.","pos":[15607,15751],"source":" For more information, see [Attached and Detached Child Tasks](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md)."},{"pos":[15760,15796],"content":"Associating State with Continuations","linkify":"Associating State with Continuations","nodes":[{"content":"Associating State with Continuations","pos":[0,36]}]},{"content":"You can associate arbitrary state with a task continuation.","pos":[15800,15859]},{"content":"The <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A&gt;</ph> method provides overloaded versions that each take an <ph id=\"ph2\">&lt;xref:System.Object&gt;</ph> value that represents the state of the continuation.","pos":[15860,16042],"source":" The <xref:System.Threading.Tasks.Task.ContinueWith%2A> method provides overloaded versions that each take an <xref:System.Object> value that represents the state of the continuation."},{"content":"You can later access this state object by using the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.AsyncState%2A?displayProperty=fullName&gt;</ph> property.","pos":[16043,16178],"source":" You can later access this state object by using the <xref:System.Threading.Tasks.Task.AsyncState%2A?displayProperty=fullName> property."},{"content":"This state object is <ph id=\"ph1\">`null`</ph> if you do not provide a value.","pos":[16179,16237],"source":" This state object is `null` if you do not provide a value."},{"content":"Continuation state is useful when you convert existing code that uses the <bpt id=\"p1\">[</bpt>Asynchronous Programming Model (APM)<ept id=\"p1\">](../../../docs/standard/asynchronous-programming-patterns/asynchronous-programming-model-apm.md)</ept> to use the TPL.","pos":[16244,16468],"source":"Continuation state is useful when you convert existing code that uses the [Asynchronous Programming Model (APM)](../../../docs/standard/asynchronous-programming-patterns/asynchronous-programming-model-apm.md) to use the TPL."},{"content":"In the APM, you typically provide object state in the <bpt id=\"p1\">*</bpt><bpt id=\"p2\">*</bpt>Begin<ept id=\"p2\">*</ept>Method<ept id=\"p1\">*</ept>** method and later access that state by using the <ph id=\"ph1\">&lt;xref:System.IAsyncResult.AsyncState%2A?displayProperty=fullName&gt;</ph> property.","pos":[16469,16664],"source":" In the APM, you typically provide object state in the **Begin*Method*** method and later access that state by using the <xref:System.IAsyncResult.AsyncState%2A?displayProperty=fullName> property."},{"content":"By using the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A&gt;</ph> method, you can preserve this state when you convert code that uses the APM to use the TPL.","pos":[16665,16820],"source":" By using the <xref:System.Threading.Tasks.Task.ContinueWith%2A> method, you can preserve this state when you convert code that uses the APM to use the TPL."},{"content":"Continuation state can also be useful when you work with <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task&gt;</ph> objects in the <ph id=\"ph2\">[!INCLUDE[vsprvs](../../../includes/vsprvs-md.md)]</ph> debugger.","pos":[16827,16994],"source":"Continuation state can also be useful when you work with <xref:System.Threading.Tasks.Task> objects in the [!INCLUDE[vsprvs](../../../includes/vsprvs-md.md)] debugger."},{"content":"For example, in the <bpt id=\"p1\">**</bpt>Parallel Tasks<ept id=\"p1\">**</ept> window, the <bpt id=\"p2\">**</bpt>Task<ept id=\"p2\">**</ept> column displays the string representation of the state object for each task.","pos":[16995,17131],"source":" For example, in the **Parallel Tasks** window, the **Task** column displays the string representation of the state object for each task."},{"content":"For more information about the <bpt id=\"p1\">**</bpt>Parallel Tasks<ept id=\"p1\">**</ept> window, see <bpt id=\"p2\">[</bpt>Using the Tasks Window<ept id=\"p2\">](/visualstudio/debugger/using-the-tasks-window)</ept>.","pos":[17132,17266],"source":" For more information about the **Parallel Tasks** window, see [Using the Tasks Window](/visualstudio/debugger/using-the-tasks-window)."},{"content":"The following example shows how to use continuation state.","pos":[17273,17331]},{"content":"It creates a chain of continuation tasks.","pos":[17332,17373]},{"content":"Each task provides the current time, a <ph id=\"ph1\">&lt;xref:System.DateTime&gt;</ph> object, for the <ph id=\"ph2\">`state`</ph> parameter of the <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.Task.ContinueWith%2A&gt;</ph> method.","pos":[17374,17535],"source":" Each task provides the current time, a <xref:System.DateTime> object, for the `state` parameter of the <xref:System.Threading.Tasks.Task.ContinueWith%2A> method."},{"content":"Each <ph id=\"ph1\">&lt;xref:System.DateTime&gt;</ph> object represents the time at which the continuation task is created.","pos":[17536,17633],"source":" Each <xref:System.DateTime> object represents the time at which the continuation task is created."},{"content":"Each task produces as its result a second <ph id=\"ph1\">&lt;xref:System.DateTime&gt;</ph> object that represents the time at which the task finishes.","pos":[17634,17758],"source":" Each task produces as its result a second <xref:System.DateTime> object that represents the time at which the task finishes."},{"content":"After all tasks finish, this example displays the creation time and the time at which each continuation task finishes.","pos":[17759,17877]},{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_ContinuationState#1<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuationstate/cs/continuationstate.cs#1)</ept><ept id=\"p1\">]</ept>","pos":[17884,18022],"source":"[!code-csharp[TPL_ContinuationState#1](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuationstate/cs/continuationstate.cs#1)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_ContinuationState#1<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuationstate/vb/continuationstate.vb#1)</ept><ept id=\"p1\">]</ept>","pos":[18024,18163],"source":"[!code-vb[TPL_ContinuationState#1](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuationstate/vb/continuationstate.vb#1)]"},{"pos":[18172,18217],"content":"Handling Exceptions Thrown from Continuations","linkify":"Handling Exceptions Thrown from Continuations","nodes":[{"content":"Handling Exceptions Thrown from Continuations","pos":[0,45]}]},{"content":"An antecedent-continuation relationship is not a parent-child relationship.","pos":[18221,18296]},{"content":"Exceptions thrown by continuations are not propagated to the antecedent.","pos":[18297,18369]},{"content":"Therefore, handle exceptions thrown by continuations as you would handle them in any other task, as follows:","pos":[18370,18478]},{"content":"You can use the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Wait%2A&gt;</ph>, <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.WaitAll%2A&gt;</ph>, or <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.Task.WaitAny%2A&gt;</ph> method, or its generic counterpart, to wait on the continuation.","pos":[18488,18708],"source":"You can use the <xref:System.Threading.Tasks.Task.Wait%2A>, <xref:System.Threading.Tasks.Task.WaitAll%2A>, or <xref:System.Threading.Tasks.Task.WaitAny%2A> method, or its generic counterpart, to wait on the continuation."},{"content":"You can wait for an antecedent and its continuations in the same <ph id=\"ph1\">`try`</ph> statement, as shown in the following example.","pos":[18709,18825],"source":" You can wait for an antecedent and its continuations in the same `try` statement, as shown in the following example."},{"pos":[18836,19089],"content":"[!code-csharp[TPL_Continuations#6](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception1.cs#6)]\n [!code-vb[TPL_Continuations#6](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception1.vb#6)]","leadings":["","    "],"nodes":[{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#6<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception1.cs#6)</ept><ept id=\"p1\">]</ept>","pos":[0,123],"source":"[!code-csharp[TPL_Continuations#6](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception1.cs#6)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#6<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception1.vb#6)</ept><ept id=\"p1\">]</ept>","pos":[125,249],"source":"[!code-vb[TPL_Continuations#6](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception1.vb#6)]"}]},{"content":"You can use a second continuation to observe the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Exception%2A&gt;</ph> property of the first continuation.","pos":[19099,19231],"source":"You can use a second continuation to observe the <xref:System.Threading.Tasks.Task.Exception%2A> property of the first continuation."},{"content":"In the following example, a task attempts to read from a non-existent file.","pos":[19232,19307]},{"content":"The continuation then displays information about the exception in the antecedent task.","pos":[19308,19394]},{"pos":[19405,19658],"content":"[!code-csharp[TPL_Continuations#4](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#4)]\n [!code-vb[TPL_Continuations#4](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#4)]","leadings":["","    "],"nodes":[{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#4<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#4)</ept><ept id=\"p1\">]</ept>","pos":[0,123],"source":"[!code-csharp[TPL_Continuations#4](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#4)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#4<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#4)</ept><ept id=\"p1\">]</ept>","pos":[125,249],"source":"[!code-vb[TPL_Continuations#4](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#4)]"}]},{"content":"Because it was run with the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> option, the continuation executes only if an exception occurs in the antecedent, and therefore it can assume that the antecedent's <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.Exception%2A&gt;</ph> property is not <ph id=\"ph3\">`null`</ph>.","pos":[19669,19978],"source":"Because it was run with the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option, the continuation executes only if an exception occurs in the antecedent, and therefore it can assume that the antecedent's <xref:System.Threading.Tasks.Task.Exception%2A> property is not `null`."},{"content":"If the continuation executes whether or not an exception is thrown in the antecedent, it would have to check whether the antecedent's <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task.Exception%2A&gt;</ph> property is not <ph id=\"ph2\">`null`</ph> before attempting to handle the exception, as the following code fragment shows.","pos":[19979,20264],"source":" If the continuation executes whether or not an exception is thrown in the antecedent, it would have to check whether the antecedent's <xref:System.Threading.Tasks.Task.Exception%2A> property is not `null` before attempting to handle the exception, as the following code fragment shows."},{"pos":[20275,20532],"content":"[!code-csharp[TPL_Continuations#11](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#11)]\n [!code-vb[TPL_Continuations#11](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#11)]","leadings":["","    "],"nodes":[{"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#11<ept id=\"p2\">](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#11)</ept><ept id=\"p1\">]</ept>","pos":[0,125],"source":"[!code-csharp[TPL_Continuations#11](../../../samples/snippets/csharp/VS_Snippets_Misc/tpl_continuations/cs/exception2.cs#11)]"},{"content":"<bpt id=\"p1\">[!code-vb</bpt><bpt id=\"p2\">[</bpt>TPL_Continuations#11<ept id=\"p2\">](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#11)</ept><ept id=\"p1\">]</ept>","pos":[127,253],"source":"[!code-vb[TPL_Continuations#11](../../../samples/snippets/visualbasic/VS_Snippets_Misc/tpl_continuations/vb/exception2.vb#11)]"}]},{"pos":[20543,20802],"content":"For more information, see <bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md)</ept> and <bpt id=\"p2\">[</bpt>NIB: How to: Handle Exceptions Thrown by Tasks<ept id=\"p2\">](http://msdn.microsoft.com/en-us/d6c47ec8-9de9-4880-beb3-ff19ae51565d)</ept>.","source":"For more information, see [Exception Handling](../../../docs/standard/parallel-programming/exception-handling-task-parallel-library.md) and [NIB: How to: Handle Exceptions Thrown by Tasks](http://msdn.microsoft.com/en-us/d6c47ec8-9de9-4880-beb3-ff19ae51565d)."},{"content":"If the continuation is an attached child task that was created by using the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName&gt;</ph> option, its exceptions will be propagated by the parent back to the calling thread, as is the case in any other attached child.","pos":[20812,21094],"source":"If the continuation is an attached child task that was created by using the <xref:System.Threading.Tasks.TaskContinuationOptions?displayProperty=fullName> option, its exceptions will be propagated by the parent back to the calling thread, as is the case in any other attached child."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Attached and Detached Child Tasks<ept id=\"p1\">](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md)</ept>.","pos":[21095,21239],"source":" For more information, see [Attached and Detached Child Tasks](../../../docs/standard/parallel-programming/attached-and-detached-child-tasks.md)."},{"pos":[21248,21256],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"pos":[21260,21363],"content":"<bpt id=\"p1\">[</bpt>Task Parallel Library (TPL)<ept id=\"p1\">](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md)</ept>","source":"[Task Parallel Library (TPL)](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md)"}]}