{"content":"---\ntitle: \"57395 - ShipAssertExceptionMessage\"\nms.date: \"03/30/2017\"\nms.assetid: 37f0c15b-e34e-42fe-8f86-b122e592add5\n---\n# 57395 - ShipAssertExceptionMessage\n## Properties  \n  \n|||  \n|-|-|  \n|ID|57395|  \n|Keywords|Infrastructure|  \n|Level|Error|  \n|Channel|Microsoft-Windows-Application Server-Applications/Analytic|  \n  \n## Description  \n This event is emitted when an unexpected failure occurred.  \n  \n## Message  \n An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: %1.  \n  \n## Details\n","nodes":[{"pos":[4,118],"embed":true,"restype":"x-metadata","content":"title: \"57395 - ShipAssertExceptionMessage\"\nms.date: \"03/30/2017\"\nms.assetid: 37f0c15b-e34e-42fe-8f86-b122e592add5","nodes":[{"content":"57395 - ShipAssertExceptionMessage","nodes":[{"pos":[0,34],"content":"57395 - ShipAssertExceptionMessage","nodes":[{"content":"57395 - ShipAssertExceptionMessage","pos":[0,34]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[125,159],"content":"57395 - ShipAssertExceptionMessage","linkify":"57395 - ShipAssertExceptionMessage","nodes":[{"content":"57395 - ShipAssertExceptionMessage","pos":[0,34]}]},{"pos":[163,173],"content":"Properties","linkify":"Properties","nodes":[{"content":"Properties","pos":[0,10]}]},{"content":"ID","pos":[194,196]},{"content":"57395","pos":[197,202]},{"content":"Keywords","pos":[207,215]},{"content":"Infrastructure","pos":[216,230]},{"content":"Level","pos":[235,240]},{"content":"Error","pos":[241,246]},{"content":"Channel","pos":[251,258]},{"content":"Microsoft-Windows-Application Server-Applications/Analytic","pos":[259,317]},{"pos":[327,338],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"This event is emitted when an unexpected failure occurred.","pos":[342,400]},{"pos":[409,416],"content":"Message","linkify":"Message","nodes":[{"content":"Message","pos":[0,7]}]},{"content":"An unexpected failure occurred.","pos":[420,451]},{"content":"Applications should not attempt to handle this error.","pos":[452,505]},{"content":"For diagnostic purposes, this English message is associated with the failure: %1.","pos":[506,587]},{"pos":[596,603],"content":"Details","linkify":"Details","nodes":[{"content":"Details","pos":[0,7]}]}]}