{"content":"---\ntitle: \"How to: Register Callbacks for Cancellation Requests | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: dotnet-standard\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nhelpviewer_keywords: \n  - \"cancellation, how to register callbacks\"\nms.assetid: 8838dd75-18ed-4b8b-b322-cd4531faac64\ncaps.latest.revision: 9\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\nmanager: \"wpickett\"\n---\n# How to: Register Callbacks for Cancellation Requests\nThe following example shows how to register a delegate that will be invoked when a <xref:System.Threading.CancellationToken.IsCancellationRequested%2A> property becomes true due to a call to <xref:System.Threading.CancellationTokenSource.Cancel%2A> on the object that created the token. Use this technique for cancelling asynchronous operations that do not natively support the unified cancellation framework, and for unblocking methods that might be waiting for an asynchronous operation to finish.  \n  \n> [!NOTE]\n>  When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.  \n  \n## Example  \n In the following example, the <xref:System.Net.WebClient.CancelAsync%2A> method is registered as the method to be invoked when cancellation is requested through the cancellation token.  \n  \n [!code-csharp[Conceptual.Cancellation.Callback#1](../../../samples/snippets/csharp/VS_Snippets_CLR/conceptual.cancellation.callback/cs/howtoexample1.cs#1)]\n [!code-vb[Conceptual.Cancellation.Callback#1](../../../samples/snippets/visualbasic/VS_Snippets_CLR/conceptual.cancellation.callback/vb/howtoexample1.vb#1)]  \n  \n If cancellation has already been requested when the callback is registered, the callback is still guaranteed to be called. In this particular case, the <xref:System.Net.WebClient.CancelAsync%2A> method will do nothing if no asynchronous operation is in progress, so it is always safe to call the method.  \n  \n## See Also  \n [Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)","nodes":[{"pos":[4,433],"embed":true,"restype":"x-metadata","content":"title: \"How to: Register Callbacks for Cancellation Requests | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: dotnet-standard\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nhelpviewer_keywords: \n  - \"cancellation, how to register callbacks\"\nms.assetid: 8838dd75-18ed-4b8b-b322-cd4531faac64\ncaps.latest.revision: 9\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\nmanager: \"wpickett\"","nodes":[{"content":"How to: Register Callbacks for Cancellation Requests | Microsoft Docs","nodes":[{"pos":[0,69],"content":"How to: Register Callbacks for Cancellation Requests | Microsoft Docs","nodes":[{"content":"How to: Register Callbacks for Cancellation Requests | Microsoft Docs","pos":[0,69]}]}],"path":["title"]}],"yml":true},{"pos":[440,492],"content":"How to: Register Callbacks for Cancellation Requests","linkify":"How to: Register Callbacks for Cancellation Requests","nodes":[{"content":"How to: Register Callbacks for Cancellation Requests","pos":[0,52]}]},{"content":"The following example shows how to register a delegate that will be invoked when a <ph id=\"ph1\">&lt;xref:System.Threading.CancellationToken.IsCancellationRequested%2A&gt;</ph> property becomes true due to a call to <ph id=\"ph2\">&lt;xref:System.Threading.CancellationTokenSource.Cancel%2A&gt;</ph> on the object that created the token.","pos":[493,779],"source":"The following example shows how to register a delegate that will be invoked when a <xref:System.Threading.CancellationToken.IsCancellationRequested%2A> property becomes true due to a call to <xref:System.Threading.CancellationTokenSource.Cancel%2A> on the object that created the token."},{"content":"Use this technique for cancelling asynchronous operations that do not natively support the unified cancellation framework, and for unblocking methods that might be waiting for an asynchronous operation to finish.","pos":[780,992]},{"pos":[1000,1486],"content":"[!NOTE]\n When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","leadings":["","> "],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","pos":[9,484],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\"","pos":[0,185]},{"content":"This error is benign.","pos":[186,207]},{"content":"You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below.","pos":[208,329]},{"content":"To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under <bpt id=\"p1\">**</bpt>Tools, Options, Debugging, General<ept id=\"p1\">**</ept>.","pos":[330,475],"source":" To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**."}]}]},{"pos":[1495,1502],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"In the following example, the <ph id=\"ph1\">&lt;xref:System.Net.WebClient.CancelAsync%2A&gt;</ph> method is registered as the method to be invoked when cancellation is requested through the cancellation token.","pos":[1506,1690],"source":"In the following example, the <xref:System.Net.WebClient.CancelAsync%2A> method is registered as the method to be invoked when cancellation is requested through the cancellation token."},{"content":"If cancellation has already been requested when the callback is registered, the callback is still guaranteed to be called.","pos":[2017,2139]},{"content":"In this particular case, the <ph id=\"ph1\">&lt;xref:System.Net.WebClient.CancelAsync%2A&gt;</ph> method will do nothing if no asynchronous operation is in progress, so it is always safe to call the method.","pos":[2140,2320],"source":" In this particular case, the <xref:System.Net.WebClient.CancelAsync%2A> method will do nothing if no asynchronous operation is in progress, so it is always safe to call the method."},{"pos":[2329,2337],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"pos":[2341,2443],"content":"<bpt id=\"p1\">[</bpt>Cancellation in Managed Threads<ept id=\"p1\">](../../../docs/standard/threading/cancellation-in-managed-threads.md)</ept>","source":"[Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)"}]}