{"content":"---\ntitle: \"<ThrowUnobservedTaskExceptions> Element\"\nms.date: \"03/30/2017\"\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"ThrowUnobservedTaskExceptions element\"\n  - \"<ThrowUnobservedTaskExceptions> element\"\nms.assetid: cea7e588-8b8d-48d2-9ad5-8feaf3642c18\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\n---\n# \\<ThrowUnobservedTaskExceptions> Element\nSpecifies whether unhandled task exceptions should terminate a running process.  \n  \n \\<configuration>  \n\\<runtime>  \n\\<ThrowUnobservedTaskExceptions>  \n  \n## Syntax  \n  \n```xml  \n<ThrowUnobservedTaskExceptions  \n   enabled=\"true|false\"/>  \n```  \n  \n## Attributes and Elements  \n The following sections describe attributes, child elements, and parent elements.  \n  \n### Attributes  \n  \n|Attribute|Description|  \n|---------------|-----------------|  \n|`enabled`|Required attribute.<br /><br /> Specifies whether unhandled task exceptions should terminate the running process.|  \n  \n## enabled Attribute  \n  \n|Value|Description|  \n|-----------|-----------------|  \n|`false`|Does not terminate the running process for an unhandled task exception. This is the default.|  \n|`true`|Terminates the running process for an unhandled task exception.|  \n  \n### Child Elements  \n None.  \n  \n### Parent Elements  \n  \n|Element|Description|  \n|-------------|-----------------|  \n|`configuration`|The root element in every configuration file used by the common language runtime and .NET Framework applications.|  \n|`runtime`|Contains information about runtime initialization options.|  \n|||  \n  \n## Remarks  \n If an exception that is associated with a <xref:System.Threading.Tasks.Task> has not been observed, there is no <xref:System.Threading.Tasks.Task.Wait%2A> operation, the parent is not attached, and the <xref:System.Threading.Tasks.Task.Exception%2A?displayProperty=nameWithType> property was not read the task exception is considered to be unobserved.  \n  \n In the [!INCLUDE[net_v40_long](../../../../../includes/net-v40-long-md.md)], by default, if a <xref:System.Threading.Tasks.Task> that has an unobserved exception is garbage collected, the finalizer throws an exception and terminates the process. The termination of the process is determined by the timing of garbage collection and finalization.  \n  \n To make it easier for developers to write asynchronous code based on tasks, the [!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)] changes this default behavior for unobserved exceptions. Unobserved exceptions still cause the <xref:System.Threading.Tasks.TaskScheduler.UnobservedTaskException> event to be raised, but by default, the process does not terminate. Instead, the exception is ignored after the event is raised, regardless of whether an event handler observes the exception.  \n  \n In the [!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)], you can use the [\\<ThrowUnobservedTaskExceptions> element](../../../../../docs/framework/configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element.md) in an application configuration file to enable the [!INCLUDE[net_v40_short](../../../../../includes/net-v40-short-md.md)] behavior of throwing an exception.  \n  \n You can also specify the exception behavior in one of the following ways:  \n  \n-   By setting the environment variable `COMPlus_ThrowUnobservedTaskExceptions` (`set COMPlus_ThrowUnobservedTaskExceptions=1`).  \n  \n-   By setting the registry DWORD value ThrowUnobservedTaskExceptions = 1 in the HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\\\.NETFramework key.  \n  \n## Example  \n The following example shows how to enable the throwing of exceptions in tasks by using an application configuration file.  \n  \n```xml  \n<configuration>   \n    <runtime>   \n        <ThrowUnobservedTaskExceptions enabled=\"true\"/>   \n    </runtime>   \n</configuration>  \n```  \n  \n## Example  \n The following example demonstrates how an unobserved exception is thrown from a task. The code must be run as a released program to work correctly.  \n  \n [!code-csharp[ThrowUnobservedTaskExceptions#1](../../../../../samples/snippets/csharp/VS_Snippets_CLR/throwunobservedtaskexceptions/cs/program.cs#1)]\n [!code-vb[ThrowUnobservedTaskExceptions#1](../../../../../samples/snippets/visualbasic/VS_Snippets_CLR/throwunobservedtaskexceptions/vb/program.vb#1)]  \n  \n## See also\n\n- [Runtime Settings Schema](../../../../../docs/framework/configure-apps/file-schema/runtime/index.md)\n- [Configuration File Schema](../../../../../docs/framework/configure-apps/file-schema/index.md)\n","nodes":[{"pos":[4,309],"embed":true,"restype":"x-metadata","content":"title: \"<ThrowUnobservedTaskExceptions> Element\"\nms.date: \"03/30/2017\"\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"ThrowUnobservedTaskExceptions element\"\n  - \"<ThrowUnobservedTaskExceptions> element\"\nms.assetid: cea7e588-8b8d-48d2-9ad5-8feaf3642c18\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"","nodes":[{"content":"<ThrowUnobservedTaskExceptions> Element","nodes":[{"pos":[0,39],"content":"<ph id=\"ph1\">&lt;ThrowUnobservedTaskExceptions&gt;</ph> Element","source":"<ThrowUnobservedTaskExceptions> Element"}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[316,356],"content":"\\<ThrowUnobservedTaskExceptions> Element","linkify":"\\<ThrowUnobservedTaskExceptions> Element","nodes":[{"content":"<ph id=\"ph1\">\\&lt;</ph>ThrowUnobservedTaskExceptions&gt; Element","pos":[0,40],"source":"\\<ThrowUnobservedTaskExceptions> Element"}]},{"content":"Specifies whether unhandled task exceptions should terminate a running process.","pos":[357,436]},{"content":"<ph id=\"ph1\">\\&lt;</ph>configuration&gt;","pos":[443,459],"source":"\\<configuration>"},{"content":"<ph id=\"ph1\">\\&lt;</ph>runtime&gt;","pos":[462,472],"source":"\\<runtime>"},{"content":"<ph id=\"ph1\">\\&lt;</ph>ThrowUnobservedTaskExceptions&gt;","pos":[475,507],"source":"\\<ThrowUnobservedTaskExceptions>"},{"pos":[516,522],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[610,633],"content":"Attributes and Elements","linkify":"Attributes and Elements","nodes":[{"content":"Attributes and Elements","pos":[0,23]}]},{"content":"The following sections describe attributes, child elements, and parent elements.","pos":[637,717]},{"pos":[727,737],"content":"Attributes","linkify":"Attributes","nodes":[{"content":"Attributes","pos":[0,10]}]},{"content":"Attribute","pos":[744,753]},{"content":"Description","pos":[754,765]},{"content":"Required attribute.","pos":[818,837]},{"content":"Specifies whether unhandled task exceptions should terminate the running process.","pos":[850,931]},{"pos":[941,958],"content":"enabled Attribute","linkify":"enabled Attribute","nodes":[{"content":"enabled Attribute","pos":[0,17]}]},{"content":"Value","pos":[965,970]},{"content":"Description","pos":[971,982]},{"content":"Does not terminate the running process for an unhandled task exception.","pos":[1029,1100]},{"content":"This is the default.","pos":[1101,1121]},{"content":"Terminates the running process for an unhandled task exception.","pos":[1133,1196]},{"pos":[1207,1221],"content":"Child Elements","linkify":"Child Elements","nodes":[{"content":"Child Elements","pos":[0,14]}]},{"content":"None.","pos":[1225,1230]},{"pos":[1240,1255],"content":"Parent Elements","linkify":"Parent Elements","nodes":[{"content":"Parent Elements","pos":[0,15]}]},{"content":"Element","pos":[1262,1269]},{"content":"Description","pos":[1270,1281]},{"content":"The root element in every configuration file used by the common language runtime and .NET Framework applications.","pos":[1338,1451]},{"content":"Contains information about runtime initialization options.","pos":[1466,1524]},{"pos":[1540,1547],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"pos":[1551,1902],"content":"If an exception that is associated with a <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.Task&gt;</ph> has not been observed, there is no <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task.Wait%2A&gt;</ph> operation, the parent is not attached, and the <ph id=\"ph3\">&lt;xref:System.Threading.Tasks.Task.Exception%2A?displayProperty=nameWithType&gt;</ph> property was not read the task exception is considered to be unobserved.","source":"If an exception that is associated with a <xref:System.Threading.Tasks.Task> has not been observed, there is no <xref:System.Threading.Tasks.Task.Wait%2A> operation, the parent is not attached, and the <xref:System.Threading.Tasks.Task.Exception%2A?displayProperty=nameWithType> property was not read the task exception is considered to be unobserved."},{"content":"In the <ph id=\"ph1\">[!INCLUDE[net_v40_long](../../../../../includes/net-v40-long-md.md)]</ph>, by default, if a <ph id=\"ph2\">&lt;xref:System.Threading.Tasks.Task&gt;</ph> that has an unobserved exception is garbage collected, the finalizer throws an exception and terminates the process.","pos":[1909,2154],"source":"In the [!INCLUDE[net_v40_long](../../../../../includes/net-v40-long-md.md)], by default, if a <xref:System.Threading.Tasks.Task> that has an unobserved exception is garbage collected, the finalizer throws an exception and terminates the process."},{"content":"The termination of the process is determined by the timing of garbage collection and finalization.","pos":[2155,2253]},{"content":"To make it easier for developers to write asynchronous code based on tasks, the <ph id=\"ph1\">[!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)]</ph> changes this default behavior for unobserved exceptions.","pos":[2260,2455],"source":"To make it easier for developers to write asynchronous code based on tasks, the [!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)] changes this default behavior for unobserved exceptions."},{"content":"Unobserved exceptions still cause the <ph id=\"ph1\">&lt;xref:System.Threading.Tasks.TaskScheduler.UnobservedTaskException&gt;</ph> event to be raised, but by default, the process does not terminate.","pos":[2456,2629],"source":" Unobserved exceptions still cause the <xref:System.Threading.Tasks.TaskScheduler.UnobservedTaskException> event to be raised, but by default, the process does not terminate."},{"content":"Instead, the exception is ignored after the event is raised, regardless of whether an event handler observes the exception.","pos":[2630,2753]},{"pos":[2760,3149],"content":"In the <ph id=\"ph1\">[!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)]</ph>, you can use the <bpt id=\"p1\">[</bpt><ph id=\"ph2\">\\&lt;</ph>ThrowUnobservedTaskExceptions&gt; element<ept id=\"p1\">](../../../../../docs/framework/configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element.md)</ept> in an application configuration file to enable the <ph id=\"ph3\">[!INCLUDE[net_v40_short](../../../../../includes/net-v40-short-md.md)]</ph> behavior of throwing an exception.","source":"In the [!INCLUDE[net_v45](../../../../../includes/net-v45-md.md)], you can use the [\\<ThrowUnobservedTaskExceptions> element](../../../../../docs/framework/configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element.md) in an application configuration file to enable the [!INCLUDE[net_v40_short](../../../../../includes/net-v40-short-md.md)] behavior of throwing an exception."},{"content":"You can also specify the exception behavior in one of the following ways:","pos":[3156,3229]},{"pos":[3239,3363],"content":"By setting the environment variable <ph id=\"ph1\">`COMPlus_ThrowUnobservedTaskExceptions`</ph> (<ph id=\"ph2\">`set COMPlus_ThrowUnobservedTaskExceptions=1`</ph>).","source":"By setting the environment variable `COMPlus_ThrowUnobservedTaskExceptions` (`set COMPlus_ThrowUnobservedTaskExceptions=1`)."},{"content":"By setting the registry DWORD value ThrowUnobservedTaskExceptions = 1 in the HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft<ph id=\"ph1\">\\\\</ph>.NETFramework key.","pos":[3373,3507],"source":"By setting the registry DWORD value ThrowUnobservedTaskExceptions = 1 in the HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\\\.NETFramework key."},{"pos":[3516,3523],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following example shows how to enable the throwing of exceptions in tasks by using an application configuration file.","pos":[3527,3648]},{"pos":[3807,3814],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following example demonstrates how an unobserved exception is thrown from a task.","pos":[3818,3903]},{"content":"The code must be run as a released program to work correctly.","pos":[3904,3965]},{"pos":[4282,4290],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[4294,4394],"content":"<bpt id=\"p1\">[</bpt>Runtime Settings Schema<ept id=\"p1\">](../../../../../docs/framework/configure-apps/file-schema/runtime/index.md)</ept>","source":"[Runtime Settings Schema](../../../../../docs/framework/configure-apps/file-schema/runtime/index.md)"},{"pos":[4397,4491],"content":"<bpt id=\"p1\">[</bpt>Configuration File Schema<ept id=\"p1\">](../../../../../docs/framework/configure-apps/file-schema/index.md)</ept>","source":"[Configuration File Schema](../../../../../docs/framework/configure-apps/file-schema/index.md)"}]}