{"content":"---\ntitle: \"System.ServiceModel.CommunicationObjectCloseFailed | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"dotnet-clr\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: 60270eab-6f57-4136-bec5-62d3edd23880\ncaps.latest.revision: 6\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"\n---\n# System.ServiceModel.CommunicationObjectCloseFailed\nA communication object failed to close.  \n  \n## Description  \n A communication object failed to close because an exception was thrown during the execution of its Close method. Another nearby trace might contain details about the exception.  \n  \n## See Also  \n [Tracing](../../../../../docs/framework/wcf/diagnostics/tracing/index.md)   \n [Using Tracing to Troubleshoot Your Application](../../../../../docs/framework/wcf/diagnostics/tracing/using-tracing-to-troubleshoot-your-application.md)   \n [Administration and Diagnostics](../../../../../docs/framework/wcf/diagnostics/index.md)","nodes":[{"pos":[4,370],"nodes":[{"content":"System.ServiceModel.CommunicationObjectCloseFailed | Microsoft Docs","nodes":[{"pos":[0,67],"content":"System.ServiceModel.CommunicationObjectCloseFailed | Microsoft Docs","nodes":[{"content":"System.ServiceModel.CommunicationObjectCloseFailed | Microsoft Docs","pos":[0,67]}]}],"pos":[6,76],"yaml":true}],"content":"title: \"System.ServiceModel.CommunicationObjectCloseFailed | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"dotnet-clr\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: 60270eab-6f57-4136-bec5-62d3edd23880\ncaps.latest.revision: 6\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"","yamlblock":true},{"pos":[377,427],"content":"System.ServiceModel.CommunicationObjectCloseFailed","linkify":"System.ServiceModel.CommunicationObjectCloseFailed","nodes":[{"content":"System.ServiceModel.CommunicationObjectCloseFailed","pos":[0,50]}]},{"content":"A communication object failed to close.","pos":[428,467]},{"pos":[476,487],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"A communication object failed to close because an exception was thrown during the execution of its Close method.","pos":[491,603]},{"content":"Another nearby trace might contain details about the exception.","pos":[604,667]},{"pos":[676,684],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>Tracing<ept id=\"p1\">](../../../../../docs/framework/wcf/diagnostics/tracing/index.md)</ept><ph id=\"ph1\"> </ph>","pos":[688,762],"source":"[Tracing](../../../../../docs/framework/wcf/diagnostics/tracing/index.md) "},{"content":"<bpt id=\"p1\">[</bpt>Using Tracing to Troubleshoot Your Application<ept id=\"p1\">](../../../../../docs/framework/wcf/diagnostics/tracing/using-tracing-to-troubleshoot-your-application.md)</ept><ph id=\"ph1\"> </ph>","pos":[766,920],"source":"[Using Tracing to Troubleshoot Your Application](../../../../../docs/framework/wcf/diagnostics/tracing/using-tracing-to-troubleshoot-your-application.md) "},{"content":"<bpt id=\"p1\">[</bpt>Administration and Diagnostics<ept id=\"p1\">](../../../../../docs/framework/wcf/diagnostics/index.md)</ept>","pos":[924,1012],"source":"[Administration and Diagnostics](../../../../../docs/framework/wcf/diagnostics/index.md)"}]}