{"content":"---\ntitle: \"4210 - SqlExceptionCaught | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: f0ce8af3-eb4c-48c8-b3d9-dd2f94b5574b\ncaps.latest.revision: 2\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"\n---\n# 4210 - SqlExceptionCaught\n## Properties  \n  \n|||  \n|-|-|  \n|ID|4210|  \n|Keywords|WFInstanceStore|  \n|Level|Warning|  \n|Channel|Microsoft-Windows-Application Server-Applications/Debug|  \n  \n## Description  \n Indicates a SQL exception was caught.  \n  \n## Message  \n Caught SQL Exception number %1 message %2.  \n  \n## Details  \n  \n|Data Item Name|Data Item Type|Description|  \n|--------------------|--------------------|-----------------|  \n|ErrorNumber|xs:string|The SQL error number.|  \n|ExceptionMessage|xs:string|The message from the SQL exception.|  \n|AppDomain|xs:string|The string returned by AppDomain.CurrentDomain.FriendlyName.|","nodes":[{"pos":[12,54],"content":"4210 - SqlExceptionCaught | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"4210 - SqlExceptionCaught | Microsoft Docs","pos":[0,42]}]},{"pos":[319,344],"content":"4210 - SqlExceptionCaught","linkify":"4210 - SqlExceptionCaught","nodes":[{"content":"4210 - SqlExceptionCaught","pos":[0,25]}]},{"pos":[348,358],"content":"Properties","linkify":"Properties","nodes":[{"content":"Properties","pos":[0,10]}]},{"content":"ID","pos":[379,381]},{"content":"4210","pos":[382,386]},{"content":"Keywords","pos":[391,399]},{"content":"WFInstanceStore","pos":[400,415]},{"content":"Level","pos":[420,425]},{"content":"Warning","pos":[426,433]},{"content":"Channel","pos":[438,445]},{"content":"Microsoft-Windows-Application Server-Applications/Debug","pos":[446,501]},{"pos":[511,522],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"Indicates a SQL exception was caught.","pos":[526,563]},{"pos":[572,579],"content":"Message","linkify":"Message","nodes":[{"content":"Message","pos":[0,7]}]},{"content":"Caught SQL Exception number %1 message %2.","pos":[583,625]},{"pos":[634,641],"content":"Details","linkify":"Details","nodes":[{"content":"Details","pos":[0,7]}]},{"content":"Data Item Name","pos":[648,662]},{"content":"Data Item Type","pos":[663,677]},{"content":"Description","pos":[678,689]},{"content":"ErrorNumber","pos":[758,769]},{"content":"xs:string","pos":[770,779]},{"content":"The SQL error number.","pos":[780,801]},{"content":"ExceptionMessage","pos":[806,822]},{"content":"xs:string","pos":[823,832]},{"content":"The message from the SQL exception.","pos":[833,868]},{"content":"AppDomain","pos":[873,882]},{"content":"xs:string","pos":[883,892]},{"content":"The string returned by AppDomain.CurrentDomain.FriendlyName.","pos":[893,953]}]}