{"content":"---\ntitle: \"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39; | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30392\"\n  - \"bc30392\"\nhelpviewer_keywords: \n  - \"BC30392\"\nms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803\ncaps.latest.revision: 7\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# &#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39;\n`Catch` can only intercept exceptions, and you have attempted to catch something that is not derived from an exception.  \n  \n **Error ID:** BC30392  \n  \n## To correct this error  \n  \n1.  Remove the `Catch` statement, or change the target of the `Catch` to an actual exception.  \n  \n## See Also  \n [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   \n [Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)","nodes":[{"pos":[4,700],"nodes":[{"content":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39; | Microsoft Docs","nodes":[{"pos":[0,179],"content":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39; | Microsoft Docs","nodes":[{"content":"&amp;#39;Catch&amp;#39; cannot catch type &amp;#39;<ph id=\"ph1\">&amp;lt;</ph>typename<ph id=\"ph2\">&amp;gt;</ph>&amp;#39; because it is not &amp;#39;System.Exception&amp;#39; or a class that inherits from &amp;#39;System.Exception&amp;#39; | Microsoft Docs","pos":[0,179],"source":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39; | Microsoft Docs"}]}],"pos":[6,188],"yaml":true}],"content":"title: \"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39; | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30392\"\n  - \"bc30392\"\nhelpviewer_keywords: \n  - \"BC30392\"\nms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803\ncaps.latest.revision: 7\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"","yamlblock":true},{"pos":[707,869],"content":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39;","linkify":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39;","nodes":[{"content":"&amp;#39;Catch&amp;#39; cannot catch type &amp;#39;<ph id=\"ph1\">&amp;lt;</ph>typename<ph id=\"ph2\">&amp;gt;</ph>&amp;#39; because it is not &amp;#39;System.Exception&amp;#39; or a class that inherits from &amp;#39;System.Exception&amp;#39;","pos":[0,162],"source":"&#39;Catch&#39; cannot catch type &#39;&lt;typename&gt;&#39; because it is not &#39;System.Exception&#39; or a class that inherits from &#39;System.Exception&#39;"}]},{"pos":[870,989],"content":"<ph id=\"ph1\">`Catch`</ph> can only intercept exceptions, and you have attempted to catch something that is not derived from an exception.","source":"`Catch` can only intercept exceptions, and you have attempted to catch something that is not derived from an exception."},{"pos":[996,1017],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30392","source":"**Error ID:** BC30392"},{"pos":[1026,1047],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[1057,1146],"content":"Remove the <ph id=\"ph1\">`Catch`</ph> statement, or change the target of the <ph id=\"ph2\">`Catch`</ph> to an actual exception.","source":"Remove the `Catch` statement, or change the target of the `Catch` to an actual exception."},{"pos":[1155,1163],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept><ph id=\"ph1\"> </ph>","pos":[1167,1282],"source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md) "},{"content":"<bpt id=\"p1\">[</bpt>Structured Exception Handling Overview for Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)</ept>","pos":[1286,1413],"source":"[Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)"}]}